apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  selector:
    matchLabels:
      run: backend-feed
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: samueladekunle/udagram-api-feed:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
            memory: "1024Mi"
          limits:
            cpu: 1000m
            memory: "8192Mi"
        envFrom:
        - configMapRef:
            name: env-config
        - secretRef:
            name: env-secret